mutation AddMovieToList($listId: UUID!, $movieId: UUID!, $note: String!, $position: Int!) @auth(level: USER) {
  listMovie_insert(data: {listId: $listId, movieId: $movieId, note: $note, position: $position})
}

query GetPublicLists @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  lists(where: {public: {eq: true}}) {
    id
    name
    description
  }
}

mutation CreateReview($movieId: UUID!, $rating: Int!, $review: String!, $watchId: UUID!) @auth(level: USER) {
  review_insert(data: {movieId: $movieId, userId_expr: "auth.uid", rating: $rating, review: $review, watchId: $watchId})
}

query GetMoviesByGenre($genre: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movies(where: {genres: {includes: $genre}}) {
    id
    title
    summary
  }
}