extend type Assignment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Assignment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Assignment`.`module`. It must match the value of `Module`.`id`. See `@ref` for how to customize it.
  """
  moduleId: UUID @fdc_generated(from: "Assignment.module", purpose: IMPLICIT_REF_FIELD)
}
extend type Course {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Course", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Course`.`instructor`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  instructorId: UUID @fdc_generated(from: "Course.instructor", purpose: IMPLICIT_REF_FIELD)
}
extend type Enrollment {
  """
  ✨ Implicit foreign key field based on `Enrollment`.`student`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  studentId: UUID! @fdc_generated(from: "Enrollment.student", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Enrollment`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID! @fdc_generated(from: "Enrollment.course", purpose: IMPLICIT_REF_FIELD)
}
extend type Lesson {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Lesson", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Lesson`.`module`. It must match the value of `Module`.`id`. See `@ref` for how to customize it.
  """
  moduleId: UUID @fdc_generated(from: "Lesson.module", purpose: IMPLICIT_REF_FIELD)
}
extend type Module {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Module", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Module`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID @fdc_generated(from: "Module.course", purpose: IMPLICIT_REF_FIELD)
}
extend type Submission {
  """
  ✨ Implicit foreign key field based on `Submission`.`student`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  studentId: UUID! @fdc_generated(from: "Submission.student", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Submission`.`assignment`. It must match the value of `Assignment`.`id`. See `@ref` for how to customize it.
  """
  assignmentId: UUID! @fdc_generated(from: "Submission.assignment", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
