type User @table {
  displayName: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  photoUrl: String
  major: String
}

type Course @table {
  title: String!
  description: String!
  category: String!
  difficultyLevel: String!
  createdAt: Timestamp!
  thumbnailUrl: String
  instructor: User
}

type Enrollment @table(key: ["student", "course"]) {
  enrollmentDate: Timestamp!
  status: String!
  completionDate: Timestamp
  grade: Int
  student: User!
  course: Course!
}

type Module @table {
  title: String!
  description: String!
  orderIndex: Int!
  course: Course
}

type Lesson @table {
  title: String!
  type: String!
  contentUrl: String!
  orderIndex: Int!
  description: String
  duration: Int
  module: Module
}

type Assignment @table {
  title: String!
  description: String!
  type: String!
  dueDate: Date!
  maxScore: Int!
  module: Module
}

type Submission @table(key: ["student", "assignment"]) {
  submissionDate: Timestamp!
  score: Int!
  studentResponse: String
  feedback: String
  student: User!
  assignment: Assignment!
}